<?php

namespace Media\VideoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumVideoRepository extends EntityRepository
{
}
