security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Media\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_PHOTO, ROLE_VIDEO, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
         # On crée un pare-feu uniquement pour le formulaire
        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
  
            
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
            logout:
                path:   fos_user_security_logout
                target: /%locale%
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _test_this_user }
            
            


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /secu, roles: ROLE_USER }
        - { path: /adpic, roles: ROLE_PHOTO }
        - { path: /video, roles: ROLE_VIDEO }
        - { path: /role, roles: ROLE_ADMIN }

