<?php

namespace G5\ProjetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobImagesRepository extends EntityRepository
{
}
