<?php

namespace G5\ProjetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobsRepository extends EntityRepository {
    public function findMesJobs($user) {
        $mesAnnonces = $this->getEntityManager()
                        ->createQuery(
                                'SELECT j
                        FROM G5ProjetBundle:Jobs j
                        WHERE j.auteur = :user '
                        )->setParameter('user', $user);
        return $mesAnnonces->getResult();
    }
    
     public function findLength() {
        $mesAnnonces = $this->getEntityManager()
                        ->createQuery(
                                'SELECT COUNT(titre)
                        FROM G5ProjetBundle:Jobs
                        WHERE isActive=1
                        '
                        );
        return $mesAnnonces->getResult();
    }

}
