<?php

namespace G5\ProjetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculeReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeReponseRepository extends EntityRepository
{
}
