<?php

namespace Media\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumsRepository extends EntityRepository {

    public function ifViewers($user, $album) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a
                        FROM MediaPhotoBundle:AlbumViewers a
                        WHERE a.user = ' . $user . ' AND a.album=' . $album . '
                        '
                        )
                        ->getResult();
    }

    public function ifActiveViewers($user, $album) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a
                        FROM MediaPhotoBundle:AlbumViewers a
                        WHERE a.user = ' . $user . ' AND a.album=' . $album . '
                        AND a.isActive = 1'
                        )
                        ->getResult();
    }

    public function findViewers($id) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT c
                        FROM MediaPhotoBundle:Albums c
                        WHERE c.album = ' . $id . '
                        ORDER BY c.id ASC'
                        )
                        ->getResult();
    }

}
