<?php

namespace Media\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumViewersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumViewersRepository extends EntityRepository
{
}
