<?php

namespace Media\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesRepository extends EntityRepository {

    public function findMyMessagesReceive($id) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT m
                        FROM MediaPhotoBundle:Messages m
                        WHERE m.destinataire = ' . $id . '
                        ORDER BY m.id ASC'
                        )
                        ->getResult();
    }

    public function findMyMessagesSent($id) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT m
                        FROM MediaPhotoBundle:Messages m
                        WHERE m.source = ' . $id . '
                        ORDER BY m.id ASC'
                        )
                        ->getResult();
    }

    public function findMessage($source, $dest) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT m
                        FROM MediaPhotoBundle:Messages m
                        WHERE (m.source = ' . $source . ' AND m.destinataire =' . $dest . ' )
                        OR (m.source = ' . $dest . ' AND m.destinataire =' . $source . ')'
                        )
                        ->getResult();
    }

}
