Profil:
    type: entity
    table: profil
    fields:
        id:
            id: true
            type: bigint
            nullable: false
            generator:
                strategy: IDENTITY
        firstName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: first_name
        lastName:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: last_name
        emailAddress:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: email_address
        username:
            type: string
            length: 128
            fixed: false
            nullable: false
        algorithm:
            type: string
            length: 128
            fixed: false
            nullable: false
        salt:
            type: string
            length: 128
            fixed: false
            nullable: true
        password:
            type: string
            length: 128
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: true
            column: is_active
        isSuperAdmin:
            type: boolean
            nullable: true
            column: is_super_admin
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks: {  }
